### ISSUE TITLE
Would you like to provide dataset?

### ISSUE THREAD

**Issue by TouInnkYoku** [KasiaBartoszek/KnifeDetection#1]
Would you like to provide dataset?

**Comment by KasiaBartoszek** [comment]
Sorry for late answer, here're the datasets I finally used: 
- http://kt.agh.edu.pl/~matiolanski/KnivesImagesDatabase/?fbclid=IwAR3tXPmK3gQy1hW00p8fhvAZDbE86vVPN9qdVv3jQ5hTToR5mpku5KFjFlA 
- https://www.kaggle.com/shank885/knife-dataset

**Comment by TouInnkYoku** [comment]
Thanks a million!!!
